service: sls-devagram-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript

functions:
  register:
    handler: functions/auth.register
    events: 
      - http:
          path: register
          method: post
          cors: true
